site_name: Software Developer Bootcamp
site_description: Kaimi's Software Developer Bootcamp Materials
site_url: https://bootcamp.kaimi.dev

theme:
  name: material

plugins: 
  - search
  - meta
  - tags

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
